name: MiniGame
version: '${project.version}'
main: fr.uniformsegue.minigame.MiniGame
api-version: '1.20'
authors: [UniformSegue]
description: MiniGame pour mes potes on teste
commands:
  startOneShot:
    permission: op
  stopOneShot:
    permission: op

